import type { Metadata } from "next";
import { Rubik,  Manrope } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";




const rubik = Rubik({
  subsets: ['latin'],
  weight: ['400', '500', '700'], 
 variable: '--font-rubik',
});
const manrope = Manrope({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-manrope',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rubik.variable} `} >
        <Navbar/>
        {children}
        <h1 className={`${rubik.variable} `}>jneit</h1>
      </body>
    </html>
  );
}
